name: "scheduled-test"
on: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  lint: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./